export const products = [
  {
    id: 1,
    title: "card",
    image: "car.jpg",
    price: "$100",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 2,
    title: "card",
    image: "bike.jpg",
    price: "$99",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 3,
    title: "card",
    image: "cycle.jpg",
    price: "$20",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 3,
    title: "card",
    image: "cycle.jpg",
    price: "$20",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 3,
    title: "card",
    image: "cycle.jpg",
    price: "$20",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 3,
    title: "card",
    image: "cycle.jpg",
    price: "$20",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: 3,
    title: "card",
    image: "cycle.jpg",
    price: "$20",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
];
